const rock = 15.678;
const paper = 123.965;
const scissors = 90.2345;

const maxPrice = Math.max(rock, paper, scissors);
const minPrice = Math.min(rock, paper, scissors);
const priceTotal = rock + paper + scissors;
const integerPriceTotal =  Math.floor(rock) + Math.floor(paper) + Math.floor(scissors);
const roundedInteger =  Math.round((Math.floor(rock) + Math.floor(paper) + Math.floor(scissors)) / 100) * 100;
const isOdd = Boolean(integerPriceTotal % 2);
const change = 500 - priceTotal;
const averagePrice = ((rock + paper + scissors) / 3).toFixed(2);
const randomDiscount = Math.random();
const priceWithDiscount = (priceTotal * randomDiscount).toFixed(2);
const costPrice = Math.round(priceTotal) / 2;
const profit = (costPrice - (priceTotal - priceWithDiscount)).toFixed(2);

document.write('Max price: ', maxPrice);
document.write('<br>');
document.write('Min price: ', minPrice);
document.write('<br>');
document.write('Total price: ', priceTotal);
document.write('<br>');
document.write('Integer price: ', integerPriceTotal);
document.write('<br>');
document.write('Rounded to closest hundred: ', roundedInteger);
document.write('<br>');
document.write('Integer is odd: ', isOdd);
document.write('<br>');
document.write('Residual money: ', change);
document.write('<br>');
document.write('Average price: ', averagePrice);
document.write('<br>');
document.write('Price with discount: ', priceWithDiscount);
document.write('<br>');
document.write('Profit: ', profit);
document.write('<br>');
document.write('<br>');
document.write(`Maximum price: ${maxPrice} Minimum price: ${minPrice} Total price: ${priceTotal} Total integer price: ${integerPriceTotal} Price rounded to closest hundred: ${roundedInteger}
Is integer price odd?: ${isOdd} Residual money: ${change} Average price: ${averagePrice} Price with discount: ${priceWithDiscount} Profit: ${profit}`);
